apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitops-dr
bases:
  - ../../base

resources:
  - namespace.yaml
images:
  - name: docker.io/jaysonzhao/olademo:latest
    newTag: gitops-dr
