apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitops-dr
bases:
  - ../../base

resources:
  - namespace.yaml
images:
  - name: RESTDEMOIMAGE
    newName: docker.io/jaysonzhao/olademo
    newTag: latest
